
---
events:
  -
    kind: "find_package-v1"
    backtrace:
      - "CMakeLists.txt:12 (find_package)"
    name: "Zephyr"
    configs:
      -
        filename: "ZephyrConfig.cmake"
        kind: "cmake"
      -
        filename: "zephyr-config.cmake"
        kind: "cmake"
    version_request:
      exact: false
    settings:
      required: "required_explicit"
      quiet: false
      global: false
      policy_scope: true
      bypass_provider: false
      names:
        - "Zephyr"
      path_suffixes:
        - ""
      paths:
        CMAKE_FIND_USE_CMAKE_PATH: true
        CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
        CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
        CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
        CMAKE_FIND_USE_INSTALL_PREFIX: true
        CMAKE_FIND_USE_PACKAGE_ROOT_PATH: true
        CMAKE_FIND_USE_CMAKE_PACKAGE_REGISTRY: true
        CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY: true
        CMAKE_FIND_ROOT_PATH_MODE: "BOTH"
    candidates:
      -
        path: "/Users/eduardo/Documents/Repos/ZPLC/firmware/app/build_tests/CMakeFiles/pkgRedirects/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/Documents/Repos/ZPLC/firmware/app/build_tests/CMakeFiles/pkgRedirects/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.opencode/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.opencode/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/Library/Application Support/carapace/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/Library/Application Support/carapace/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/opt/homebrew/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/opt/homebrew/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.local/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.local/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.bun/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.bun/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/local/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/local/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.config/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.config/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/opt/homebrew/share/google-cloud-sdk/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/opt/homebrew/share/google-cloud-sdk/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.antigravity/antigravity/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Users/eduardo/.antigravity/antigravity/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/System/Cryptexes/App/usr/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/System/Cryptexes/App/usr/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Applications/Ghostty.app/Contents/MacOS/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/Applications/Ghostty.app/Contents/MacOS/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
    found: null
    search_context:
      ENV{PATH}:
        - "/Users/eduardo/.opencode/bin"
        - "/Users/eduardo/Library/Application Support/carapace/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/eduardo/.local/bin"
        - "/Users/eduardo/.opencode/bin"
        - "/Users/eduardo/.cargo/bin"
        - "/Users/eduardo/.volta/bin"
        - "/Users/eduardo/.bun/bin"
        - "/Users/eduardo/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/usr/local/bin"
        - "/Users/eduardo/.config"
        - "/usr/local/lib/*"
        - "/opt/homebrew/share/google-cloud-sdk/bin"
        - "/Users/eduardo/.antigravity/antigravity/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/Applications/Ghostty.app/Contents/MacOS"
...
