# ZPLC Project Configuration

name: Motor Control
description: Motor start/stop circuit with seal-in logic and parallel branches
version: 1.0.0
author: ZPLC Team

# Target hardware configuration
target:
  board: rpi_pico
  cpu: rp2040
  clock_mhz: 125

# Compiler settings
compiler:
  optimization: size
  debug: true
  warnings: all

# I/O Configuration
io:
  inputs:
    - name: StartPB
      address: "%I0.0"
      description: "Start pushbutton (NO)"
      pin: 2

    - name: StopPB
      address: "%I0.1"
      description: "Stop pushbutton (NC)"
      pin: 3

    - name: Overload
      address: "%I0.2"
      description: "Overload relay contact"
      pin: 4

  outputs:
    - name: MotorContactor
      address: "%Q0.0"
      description: "Motor contactor output"
      pin: 16

    - name: RunningLamp
      address: "%Q0.1"
      description: "Motor running indicator lamp"
      pin: 17

# Build tasks
tasks:
  - name: build
    description: Compile the project
    command: compile
    default: true

  - name: upload
    description: Upload to target device
    command: upload
    depends_on: build

  - name: simulate
    description: Run in WASM simulator
    command: simulate

# Entry point
entry_point: main.ld.json

# Files to include
include:
  - "*.st"
  - "*.ld.json"
  - "*.fbd.json"

exclude:
  - "*.bak"
