import type { LearnLesson, LearnLessonId } from './learnLesson';

export const learnLessonContentEnV1: readonly LearnLesson[] = Object.freeze([
    {
      id: 'motor-start-stop-safe', exampleId: 'motor_start_stop', requiredScenario: 'MotorStartStop', sourcePath: 'src/Motor.st', scenarioPath: 'tests/motor-start-stop.scenario.json',
      title: 'Safe motor start-stop', summary: 'Walk through a motor with seal-in, stop, and overload handling using the Motor Start Stop example.',
      stages: [
        { title: 'Objective', body: 'Locate the start, stop, and seal-in logic; verify that Reverse remains FALSE.', checkpoint: 'The source to inspect is src/Motor.st.' },
        { title: 'Predict', body: 'Before running, predict the motor state at 20, 40, 90, and 140 ms.', checkpoint: 'Motor.Forward: ON at 20 ms and OFF at 40, 90, and 140 ms. Motor.Reverse remains OFF.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/Motor.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the MotorStartStop scenario.', checkpoint: 'The required scenario is named MotorStartStop.' },
        { title: 'Observe', body: 'Compare the trace: EStop at 40 ms, overload at 90 ms, and stop at 140 ms.', checkpoint: 'EStop, Overload, and Stop force Motor.Forward OFF.' },
        { title: 'Reflect', body: 'The exact NEVER assertion checks logical coverage for this scenario.', checkpoint: 'It does not establish physical safety, hardware timing, or certification.' },
      ],
      scope: 'Tests provide native POSIX host evidence only; they are not hardware or HIL evidence.',
    },
    {
      id: 'pedestrian-crossing-states', exampleId: 'pedestrian_crossing', requiredScenario: 'PedestrianCrossing', sourcePath: 'src/PedestrianCrossing.st', scenarioPath: 'tests/pedestrian-crossing.scenario.json',
      title: 'Pedestrian crossing and safe states', summary: 'Walk through pedestrian-crossing states with mutually consistent vehicle and pedestrian outputs.',
      stages: [
        { title: 'Objective', body: 'Locate the states coordinating vehicles and pedestrians in src/PedestrianCrossing.st.', checkpoint: 'Each state must leave an explicit output combination.' },
        { title: 'Predict', body: 'Before running, predict the light and pedestrian-signal sequence.', checkpoint: 'green+STOP 0 ms; yellow+STOP 20; red+STOP 40; red+WALK 60; red+STOP 90; green+STOP 110.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/PedestrianCrossing.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the PedestrianCrossing scenario.', checkpoint: 'The required scenario is named PedestrianCrossing.' },
        { title: 'Observe', body: 'Review the recorded matrix in Tests and compare every sample with the prediction.', checkpoint: 'The trace shows WALK only during the red state.' },
        { title: 'Reflect', body: 'The NEVER assertion covers logically incompatible outputs only in this scenario.', checkpoint: 'It does not establish a physical crossing, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide deterministic native POSIX host evidence only; they are not physical crossing, hardware, HIL, or certification evidence.',
    },
    {
      id: 'tank-level-fault-reset', exampleId: 'tank_level', requiredScenario: 'TankLevel', sourcePath: 'src/TankLevel.st', scenarioPath: 'tests/tank-level.scenario.json',
      title: 'Tank level, faults, and reset', summary: 'Walk through level control and the fault and reset latches in the Tank Level example.',
      stages: [
        { title: 'Objective', body: 'Locate PumpLatched, FaultLatched, and ResetArmed in src/TankLevel.st.', checkpoint: 'Pump, fault, and reset memory must have explicit states.' },
        { title: 'Predict', body: 'Before running, predict the pump and alarm through the level and fault changes.', checkpoint: 'Pump ON/Alarm NORMAL 10–60 ms; Pump OFF/Alarm NORMAL 70 ms; OFF/ALARM 80–90; OFF/NORMAL 100–110; OFF/ALARM 120–130; OFF/NORMAL 140–150.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/TankLevel.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the TankLevel scenario.', checkpoint: 'The required scenario is named TankLevel.' },
        { title: 'Observe', body: 'Relate 80/100/120/140 ms to fault, reset, EStop, and recovery; Pump+Alarm must never coexist.', checkpoint: 'The recorded matrix in Tests shows every pump and alarm transition.' },
        { title: 'Reflect', body: 'The NEVER assertion covers Pump+Alarm only in this recorded scenario.', checkpoint: 'It does not establish a physical process, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide deterministic native POSIX host evidence only; they are not physical-process, hardware, HIL, or certification evidence.',
    },
    {
      id: 'conveyor-classification-jam', exampleId: 'conveyor_01', requiredScenario: 'Conveyor01', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-01.scenario.json',
      title: 'Conveyor classification and safe jam', summary: 'Walk through part classification and the safe jam lockout in the Conveyor 01 example.',
      stages: [
        { title: 'Objective', body: 'Locate Requested, Faulted, and MetalLatched; sensors belong to the plant.', checkpoint: 'The logic commands outputs only from plant-recorded sensors.' },
        { title: 'Predict', body: 'Before running, predict the belt, diverter, and fault lamp.', checkpoint: 'Belt ON 10–40; Diverter ON only 30; FaultLamp ON and Belt OFF 50–80. Reset at 60 does not release while JamDetected remains active.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/Conveyor.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only Conveyor01; do not run Tests-all because it includes ConveyorTwoParts.', checkpoint: 'The required scenario is named Conveyor01.' },
        { title: 'Observe', body: 'Review the matrix: classifier+metal 20, diverter+count=1 at 30, jam 50.', checkpoint: 'The jam turns FaultLamp on and stops Belt.' },
        { title: 'Reflect', body: 'The NEVER assertion covers DiverterCommand ON with BeltCommand OFF only in this scenario.', checkpoint: 'It does not establish a physical conveyor, jam clearance, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide deterministic native POSIX host evidence only; they are not physical conveyor, jam clearance, hardware, HIL, or certification evidence.',
    },
    {
      id: 'blinky-ladder-timer-feedback', exampleId: 'blinky', requiredScenario: 'BlinkyVisual', sourcePath: 'src/main.ld.json', scenarioPath: 'tests/blinky-visual.scenario.json',
      title: 'Ladder, TON, and output feedback', summary: 'Walk through the NC contact, TON, and output feedback in the Blinky Ladder example.',
      stages: [
        { title: 'Objective', body: 'Identify the LED_Output NC contact, BlinkTimer TON with T#500ms, and the coil in src/main.ld.', checkpoint: 'Output feedback enables the timer while LED is OFF.' },
        { title: 'Predict', body: 'Before running, follow the feedback between timer and coil.', checkpoint: 'LED OFF enables TON; BlinkTimer.Q feeds the coil; scenario requires FALLING between 10–550 ms and RISING between 10–1090 ms.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment to a rung in src/main.ld. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only BlinkyVisual.', checkpoint: 'The required scenario is named BlinkyVisual.' },
        { title: 'Observe', body: 'Review trace and table: true and false appear, and both edges pass.', checkpoint: 'Recorded evidence contains FALLING and RISING.' },
        { title: 'Reflect', body: 'Assertions cover the visual program and host scenario, not electrical period or duty cycle.', checkpoint: 'It does not establish a physical LED, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide native POSIX host evidence only; they are not physical LED, hardware timing, HIL, or certification evidence.',
    },
    {
      id: 'motor-plant-feedback', exampleId: 'motor_plant', requiredScenario: 'MotorPlant', sourcePath: 'src/MotorPlant.st', scenarioPath: 'tests/motor-plant.scenario.json',
      title: 'Command, feedback, and speed', summary: 'Separate a motor command from the run confirmation using the Motor Plant.',
      stages: [
        { title: 'Objective', body: 'Locate Requested, Command, and Running in src/MotorPlant.st.', checkpoint: 'Command reflects the request; Running also depends on AtSpeed.' },
        { title: 'Predict', body: 'Before running, distinguish the command from the confirmation.', checkpoint: '0 ms: Command/Running OFF; 10: Command ON and Running OFF; 30: both ON; 40: both OFF.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/MotorPlant.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the MotorPlant scenario.', checkpoint: 'The required scenario is named MotorPlant.' },
        { title: 'Observe', body: 'Compare 10 with 30 ms: the plant records the command before AtSpeed; Stop at 40 turns both off.', checkpoint: 'The recorded matrix and trace show the discrete speed/AtSpeed advance.' },
        { title: 'Reflect', body: 'RISING/FALLING cover this transition, and NEVER checks that Running never appears without Command in this scenario.', checkpoint: 'It does not establish inertia, a physical motor, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide deterministic native POSIX host and discrete-plant evidence only; they are not physical-motor, hardware, HIL, or certification evidence.',
    },
    {
      id: 'edge-counter-pulses', exampleId: 'edge_counter', requiredScenario: 'EdgeCounter', sourcePath: 'src/EdgeCounter.st', scenarioPath: 'tests/edge-counter.scenario.json',
      title: 'Edges and pulse counter', summary: 'Use R_TRIG and CTU to count three discrete pulses and reset the threshold.',
      stages: [
        { title: 'Objective', body: 'Locate PulseInput, Reset, Edge, Count, and CountReached in src/EdgeCounter.st.', checkpoint: 'R_TRIG turns each rising edge into a one-scan pulse; CTU counts those pulses.' },
        { title: 'Predict', body: 'Before running, predict when the counter reaches PV=3.', checkpoint: 'CountReached stays OFF at 0, 10, and 30 ms; turns ON at 50 after the third edge; returns OFF at 70 with Reset.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/EdgeCounter.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the EdgeCounter scenario.', checkpoint: 'The required scenario is named EdgeCounter.' },
        { title: 'Observe', body: 'Compare 10, 30, 50, and 70 ms with CountReached.', checkpoint: 'The third pulse reaches PV=3; Reset dominates and returns CountReached to OFF.' },
        { title: 'Reflect', body: 'The AT/RISING/FALLING assertions cover this discrete logical sequence.', checkpoint: 'They do not establish bounce, electrical pulses, hardware timing, HIL, or certification.' },
      ],
      scope: 'Tests provide native POSIX host evidence only; they are not physical-sensor, bounce, hardware, HIL, or certification evidence.',
    },
    {
      id: 'scan-cycle-one-scan-memory', exampleId: 'scan_snapshot', requiredScenario: 'ScanSnapshot', sourcePath: 'src/ScanSnapshot.st', scenarioPath: 'tests/scan-snapshot.scenario.json',
      title: 'Scan cycle and one-scan memory', summary: 'Follow how one input produces the current output and a copy delayed by one scan.',
      stages: [
        { title: 'Objective', body: 'Locate Button, Previous, Current, Delayed, and RisingPulse in src/ScanSnapshot.st.', checkpoint: 'Previous updates at the end of the scan.' },
        { title: 'Predict', body: 'Before running, predict the four recorded samples.', checkpoint: '000@0, 101@10, 010@20, 000@30.' },
        { title: 'Edit', body: 'Add only a harmless explanatory comment in src/ScanSnapshot.st. This edit is not auto-graded.', checkpoint: 'Program behavior must remain unchanged.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only the ScanSnapshot scenario.', checkpoint: 'The required scenario is named ScanSnapshot.' },
        { title: 'Observe', body: 'Compare 10, 20, and 30 ms: RisingPulse lasts one scan and Delayed keeps the delayed copy.', checkpoint: 'The pulse appears at 10 ms; Delayed appears at 20 ms and returns OFF at 30 ms.' },
        { title: 'Evidence', body: 'AT/RISING/FALLING/NEVER cover the scenario; hashes and trace belong to the host.', checkpoint: 'Recorded evidence belongs to the executed host scenario.' },
        { title: 'Reflect', body: 'Updating Previous first would break the edge detector.', checkpoint: 'Memory must retain the prior value until the end of the scan.' },
      ],
      scope: 'Tests provide native POSIX host runtime evidence with one 10 ms task; they do not establish target timing, snapshots under physical interrupts, electrical bounce, HIL, or certification.',
    },
    {
      id: 'temporal-assertions-jam-fault', exampleId: 'conveyor_01', requiredScenario: 'Conveyor01', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-01.scenario.json',
      title: 'Temporal assertions and jam fault', summary: 'Read the Conveyor01 temporal contracts and compare them with the recorded plant.',
      stages: [
        { title: 'Objective', body: 'Use src/Conveyor.st and tests/conveyor-01.scenario.json to separate the logic from its temporal contracts.', checkpoint: 'The starter must restore the host lockout before the visible scenario can pass.' },
        { title: 'Predict', body: 'Before running, predict what the two AT assertions prove. Read RISING from 20 ms within 10 ms, NEVER with the diverter active and belt off, WITHIN from 50 ms with a 0 ms window, and FOR for 30 ms.', checkpoint: 'AT requires BeltCommand, DiverterCommand, and FaultLamp OFF at 0 ms and BeltCommand ON at 10 ms. RISING reaches DiverterCommand by 30 ms; WITHIN requires Belt OFF and FaultLamp ON at 50 ms; FOR holds that state from 50 to 80 ms.' },
        { title: 'Edit', body: 'Correct the starter host lockout. Read RISING from 20 ms within 10 ms, NEVER with the diverter active and belt off, WITHIN from 50 ms with a 0 ms window, and FOR for 30 ms.', checkpoint: 'Save: RISING reaches DiverterCommand by 30 ms; WITHIN requires Belt OFF and FaultLamp ON at 50 ms; FOR holds that state from 50 to 80 ms; the visible scenario must pass with saved host evidence.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only Conveyor01.', checkpoint: 'The required scenario is named Conveyor01 and contains six assertions.' },
        { title: 'Compare', body: 'Compare assertions, trace, and recorded plant: classification happens before the jam; at 50 ms the belt stops and the fault remains active.', checkpoint: 'The recorded plant shows the discrete sequence, not a physical measurement.' },
        { title: 'Reflect', body: 'NEVER prevents an incompatible logical combination within this scenario; Reset at 60 ms does not release the fault while the injected jam remains present.', checkpoint: 'An injected jam does not establish a physical fault, physical clearance, target timing, HIL, or certification.' },
      ],
      scope: 'Tests provide native POSIX host runtime and discrete-plant evidence only; the injected jam is not a physical fault, physical clearance, target timing, HIL, or certification evidence.',
    },
    {
      id: 'conveyor-two-parts-diagnosis', exampleId: 'conveyor_01', requiredScenario: 'ConveyorTwoParts', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-two-parts.scenario.json',
      title: 'Reproducible diagnosis: two parts, one decision', summary: 'Use the versioned schedule to distinguish one metal part from one non-metal part without inventing observability.',
      stages: [
        { title: 'Locate', body: 'Locate PartAtClassifier, MetalDetected, PartAtDiverter, and MetalLatched in src/Conveyor.st.', checkpoint: 'MetalLatched sets with classifier+metal and clears when the part reaches the diverter.' },
        { title: 'Predict', body: 'The first part is metal and the second is non-metal.', checkpoint: 'Expect diversion only for the first; Belt stays active for both.' },
        { title: 'Read the schedule', body: 'The JSON schedules classifier→diverter at 20→30 ms and 50→70 ms, with a 10 ms tick through 80 ms.', checkpoint: 'The three assertions are AT@30 Belt=true/Diverter=true, AT@70 Belt=true/Diverter=false, and NEVER Diverter=true with Belt=false.' },
        { title: 'Run', body: 'In Tests, choose the saved zplc.json and run only ConveyorTwoParts.', checkpoint: 'The required scenario is named ConveyorTwoParts.' },
        { title: 'Diagnose', body: 'The Tests matrix proves host outputs: compare the 30 and 70 ms samples.', checkpoint: 'It does not prove or record inputs, physical parts, or the internal MetalLatched state.' },
        { title: 'Limits', body: 'Repeat the same scenario for a reproducible decision about host outputs.', checkpoint: 'It does not establish physical sensors or parts, target timing, hardware, HIL, or certification.' },
      ],
      scope: 'Tests provide native POSIX host runtime evidence with scenario-scheduled inputs; they are not physical sensors or parts, target timing, hardware, HIL, or certification evidence.',
    },
]);

export const learnFaultCasesEnV1: Readonly<Record<LearnLessonId, readonly string[]>> = Object.freeze({
  'motor-start-stop-safe': ['The starter loses seal-in when Start is released; implement Stop, EStop, and overload dropout.'],
  'pedestrian-crossing-states': ['The starter never enters the pedestrian phase after a request; implement mutually exclusive states.'],
  'tank-level-fault-reset': ['The starter runs through a pump fault; latch alarm and require reset before recovery.'],
  'conveyor-classification-jam': ['The starter misses the deterministic jam lockout; stop the belt while the plant reports JamDetected.'],
  'blinky-ladder-timer-feedback': ['The starter never transitions LED_Output; add a bounded TON feedback oscillator.'],
  'motor-plant-feedback': ['The starter loses Command after Start falls; retain request until Stop and gate Running with AtSpeed.'],
  'edge-counter-pulses': ['The starter never reaches the third rising edge; add R_TRIG and CTU PV=3.'],
  'scan-cycle-one-scan-memory': ['The starter has no one-scan memory; retain Previous and derive the rising pulse before updating it.'],
  'temporal-assertions-jam-fault': ['The starter intentionally misses the host jam lockout; stop Belt while JamDetected is active.'],
  'conveyor-two-parts-diagnosis': ['The starter never latches metal for the diverter; clear it only after the metal part reaches it.'],
});
