import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'bun:test';

describe('Learn panel contract', () => {
  it('selects either canonical example, copies it only through the folder action, and opens Tests without running anything', () => {
    const source = readFileSync(join(import.meta.dir, 'LearnPanel.tsx'), 'utf8');
    const lessonSource = readFileSync(join(import.meta.dir, 'learnLesson.ts'), 'utf8');
    const esContentSource = readFileSync(join(import.meta.dir, 'learnContent.es.v1.ts'), 'utf8');
    const enContentSource = readFileSync(join(import.meta.dir, 'learnContent.en.v1.ts'), 'utf8');
    expect(source).toContain('copyExampleProjectToFolder(lesson.starterExampleId)');
    expect(source).toContain("setActiveConsoleTab('tests')");
    expect(source).toContain('copyingRef.current');
    expect(source).toContain('isFileSystemAccessSupported()');
    expect(source).toContain('aria-pressed={lessonId === candidate.id}');
    expect(source).toContain("disabled={copyStatus === 'copying'}");
    expect(source).toContain('{candidate.title}');
    expect(source).toContain("setCopyStatus('idle')");
    expect(source).toContain('gradeRecordedScenarioLesson(lesson, workspaceTestPresentation)');
    expect(source).toContain('readLearnMastery()');
    expect(source).toContain("recordLearnMastery(lesson.id, { kind: 'passed', assertions: 0 }, previous)");
    expect(source).toContain('text-[var(--color-surface-900)]');
    expect(source).not.toContain('text-white');
    expect((source.match(/role="group"/g) ?? [])).toHaveLength(2);
    expect(source).not.toContain('setTimeout');
    expect(source).not.toContain('clearTimeout');
    expect(source).toContain('Completada anteriormente');
    expect(source).toContain('Previously completed');
    expect(source).toContain('data-learn-grade={grade.kind}');
    expect(source).toContain('{lesson.scope}');
    expect(source).toContain('serializeLearnMastery(mastered)');
    expect(source).toContain('parseLearnMasteryImport(await file.text())');
    expect(source).toContain(".catch(() => { if (active) { setMasteryStatus('error'); setHydrated(true); } })");
    expect(source).toContain("if (grade.kind !== 'passed' || !hydrated) return;");
    expect(source).toContain('void desktopProgress.merge([...next])');
    expect(source).toContain('file.size > 4096');
    expect(source).toContain('aria-live="polite"');
    expect(source).toContain('Exportar progreso');
    expect(source).toContain('Importar progreso');
    expect(source).toContain("'Falla a corregir:'");
    expect(source).toContain("'Regresiones incluidas:'");
    expect(esContentSource).toContain("exampleId: 'motor_start_stop'");
    expect(esContentSource).toContain("exampleId: 'pedestrian_crossing'");
    expect(esContentSource).toContain("exampleId: 'tank_level'");
    expect(esContentSource).toContain("exampleId: 'conveyor_01'");
    expect(esContentSource).toContain("exampleId: 'blinky'");
    expect(esContentSource).toContain("exampleId: 'motor_plant'");
    expect(esContentSource).toContain("exampleId: 'edge_counter'");
    expect(esContentSource).toContain("exampleId: 'scan_snapshot'");
    expect(esContentSource).toContain("id: 'temporal-assertions-jam-fault'");
    expect(esContentSource).toContain("title: 'Assertions temporales y falla por atasco'");
    expect(enContentSource).toContain("title: 'Temporal assertions and jam fault'");
    expect(esContentSource).toContain("exampleId: 'conveyor_01'");
    expect(esContentSource).toContain("id: 'conveyor-two-parts-diagnosis'");
    expect(esContentSource).toContain("requiredScenario: 'ConveyorTwoParts'");
    expect(esContentSource).toContain("scenarioPath: 'tests/conveyor-two-parts.scenario.json'");
    expect(esContentSource).toContain("title: 'Diagnóstico reproducible: dos piezas, una decisión'");
    expect(enContentSource).toContain("title: 'Reproducible diagnosis: two parts, one decision'");
    expect(lessonSource).not.toContain('rawLearnLessonCatalog');
    expect(lessonSource).not.toContain('Arranque y parada seguros');
    expect(lessonSource).not.toContain('Safe start and stop');
    expect(lessonSource).not.toContain('Safe motor start-stop');
    expect(esContentSource).toContain('Arranque y parada seguros');
    expect(enContentSource).toContain('Safe motor start-stop');
    expect(source).not.toMatch(/localStorage|workspaceTests\.|runWorkspaceTests|flash|deploy|force|RUN\/STOP|local-first|LLM|mark complete|reset mastery/i);
  });
});
