import type { LearnLesson, LearnLessonId } from './learnLesson';

export const learnLessonContentEsV1: readonly LearnLesson[] = Object.freeze([
    {
      id: 'motor-start-stop-safe', exampleId: 'motor_start_stop', requiredScenario: 'MotorStartStop', sourcePath: 'src/Motor.st', scenarioPath: 'tests/motor-start-stop.scenario.json',
      title: 'Arranque y parada seguros', summary: 'Recorré un motor con enclavamiento, parada y sobrecarga usando el ejemplo Motor Start Stop.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá la lógica de marcha, parada y seal-in; verificá que Reverse permanece FALSE.', checkpoint: 'La fuente a revisar es src/Motor.st.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá el estado del motor en 20, 40, 90 y 140 ms.', checkpoint: 'Motor.Forward: ON a 20 ms y OFF a 40, 90 y 140 ms. Motor.Reverse permanece OFF.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/Motor.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario MotorStartStop.', checkpoint: 'El escenario requerido se llama MotorStartStop.' },
        { title: 'Observá', body: 'Compará la traza: EStop a 40 ms, sobrecarga a 90 ms y parada a 140 ms.', checkpoint: 'EStop, Overload y Stop fuerzan Motor.Forward OFF.' },
        { title: 'Reflexioná', body: 'La assertion exacta NEVER comprueba cobertura lógica de este escenario.', checkpoint: 'No demuestra seguridad física, temporización de hardware ni certificación.' },
      ],
      scope: 'La evidencia de Tests es del host nativo POSIX; no es evidencia de hardware ni HIL.',
    },
    {
      id: 'pedestrian-crossing-states', exampleId: 'pedestrian_crossing', requiredScenario: 'PedestrianCrossing', sourcePath: 'src/PedestrianCrossing.st', scenarioPath: 'tests/pedestrian-crossing.scenario.json',
      title: 'Cruce peatonal y estados seguros', summary: 'Recorré estados de cruce peatonal con salidas de vehículo y peatón mutuamente consistentes.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá los estados que coordinan vehículos y peatones en src/PedestrianCrossing.st.', checkpoint: 'Cada estado debe dejar una combinación de salidas explícita.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá la secuencia de luces y señal peatonal.', checkpoint: 'verde+STOP 0 ms; amarillo+STOP 20; rojo+STOP 40; rojo+WALK 60; rojo+STOP 90; verde+STOP 110.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/PedestrianCrossing.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario PedestrianCrossing.', checkpoint: 'El escenario requerido se llama PedestrianCrossing.' },
        { title: 'Observá', body: 'Revisá la matriz registrada en Tests y compará cada muestra con la predicción.', checkpoint: 'La traza muestra el cambio a WALK sólo durante el estado rojo.' },
        { title: 'Reflexioná', body: 'La assertion NEVER cubre salidas incompatibles lógicas sólo en este escenario.', checkpoint: 'No demuestra un cruce físico, temporización de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es determinística del host nativo POSIX; no es evidencia de cruce físico, hardware, HIL ni certificación.',
    },
    {
      id: 'tank-level-fault-reset', exampleId: 'tank_level', requiredScenario: 'TankLevel', sourcePath: 'src/TankLevel.st', scenarioPath: 'tests/tank-level.scenario.json',
      title: 'Nivel de tanque, fallas y reset', summary: 'Recorré el control de nivel y los enclavamientos de falla y reset del ejemplo Tank Level.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá PumpLatched, FaultLatched y ResetArmed en src/TankLevel.st.', checkpoint: 'Las memorias de bomba, falla y reset deben tener estados explícitos.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá la bomba y alarma durante los cambios de nivel y falla.', checkpoint: 'Pump ON/Alarm NORMAL 10–60 ms; Pump OFF/Alarm NORMAL 70 ms; OFF/ALARM 80–90; OFF/NORMAL 100–110; OFF/ALARM 120–130; OFF/NORMAL 140–150.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/TankLevel.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario TankLevel.', checkpoint: 'El escenario requerido se llama TankLevel.' },
        { title: 'Observá', body: 'Relacioná 80/100/120/140 ms con fault, reset, EStop y la recuperación; nunca deben coexistir Pump+Alarm.', checkpoint: 'La matriz registrada en Tests muestra cada transición de bomba y alarma.' },
        { title: 'Reflexioná', body: 'La assertion NEVER cubre Pump+Alarm sólo en este escenario registrado.', checkpoint: 'No demuestra un proceso físico, temporización de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es determinística del host nativo POSIX; no es evidencia de proceso físico, hardware, HIL ni certificación.',
    },
    {
      id: 'conveyor-classification-jam', exampleId: 'conveyor_01', requiredScenario: 'Conveyor01', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-01.scenario.json',
      title: 'Cinta de clasificación y atasco seguro', summary: 'Recorré la clasificación de piezas y el bloqueo seguro por atasco del ejemplo Conveyor 01.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá Requested, Faulted y MetalLatched; los sensores pertenecen a la plant.', checkpoint: 'La lógica sólo manda salidas a partir de sensores registrados por la plant.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá la cinta, desviador y lámpara de falla.', checkpoint: 'Belt ON 10–40; Diverter ON sólo 30; FaultLamp ON y Belt OFF 50–80. Reset a 60 no libera mientras JamDetected sigue activo.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/Conveyor.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente Conveyor01; no ejecutes Tests-all porque incluye ConveyorTwoParts.', checkpoint: 'El escenario requerido se llama Conveyor01.' },
        { title: 'Observá', body: 'Revisá la matriz: classifier+metal 20, diverter+count=1 a 30, jam 50.', checkpoint: 'El atasco enciende FaultLamp y detiene Belt.' },
        { title: 'Reflexioná', body: 'La assertion NEVER cubre DiverterCommand ON con BeltCommand OFF sólo en este escenario.', checkpoint: 'No demuestra cinta física, despeje de atasco, temporización de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es determinística del host nativo POSIX; no es evidencia de cinta física, despeje de atasco, hardware, HIL ni certificación.',
    },
    {
      id: 'blinky-ladder-timer-feedback', exampleId: 'blinky', requiredScenario: 'BlinkyVisual', sourcePath: 'src/main.ld.json', scenarioPath: 'tests/blinky-visual.scenario.json',
      title: 'Ladder, TON y realimentación de salida', summary: 'Recorré el contacto NC, TON y realimentación de salida del ejemplo Ladder de Blinky.',
      stages: [
        { title: 'Objetivo', body: 'Identificá el contacto NC LED_Output, TON BlinkTimer con T#500ms y la coil en src/main.ld.', checkpoint: 'La salida se realimenta para habilitar el temporizador cuando LED está OFF.' },
        { title: 'Predecí', body: 'Antes de ejecutar, seguí la realimentación entre temporizador y coil.', checkpoint: 'LED OFF habilita TON; BlinkTimer.Q alimenta coil; el escenario exige FALLING entre 10–550 ms y RISING entre 10–1090 ms.' },
        { title: 'Editá', body: 'Agregá sólo un comentario explicativo inocuo a un rung en src/main.ld. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente BlinkyVisual.', checkpoint: 'El escenario requerido se llama BlinkyVisual.' },
        { title: 'Observá', body: 'Revisá trace y tabla: aparecen true y false, y pasan ambos flancos.', checkpoint: 'La evidencia registrada contiene FALLING y RISING.' },
        { title: 'Reflexioná', body: 'Las assertions cubren programa visual y escenario host, no período ni duty eléctrico.', checkpoint: 'No demuestra LED físico, timing de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es del host nativo POSIX; no es evidencia de LED físico, timing de hardware, HIL ni certificación.',
    },
    {
      id: 'motor-plant-feedback', exampleId: 'motor_plant', requiredScenario: 'MotorPlant', sourcePath: 'src/MotorPlant.st', scenarioPath: 'tests/motor-plant.scenario.json',
      title: 'Comando, realimentación y velocidad', summary: 'Separá la orden del motor de la confirmación de marcha usando la planta Motor Plant.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá Requested, Command y Running en src/MotorPlant.st.', checkpoint: 'Command expresa la orden; Running depende además de AtSpeed.' },
        { title: 'Predecí', body: 'Antes de ejecutar, diferenciá la orden de la confirmación.', checkpoint: '0 ms: Command/Running OFF; 10: Command ON y Running OFF; 30: ambos ON; 40: ambos OFF.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/MotorPlant.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario MotorPlant.', checkpoint: 'El escenario requerido se llama MotorPlant.' },
        { title: 'Observá', body: 'Compará 10 con 30 ms: la planta registra orden antes de AtSpeed; Stop a 40 apaga ambos.', checkpoint: 'La matriz y la traza registradas muestran el avance discreto de speed/AtSpeed.' },
        { title: 'Reflexioná', body: 'RISING/FALLING cubren esta transición y NEVER comprueba que Running no aparezca sin Command dentro de este escenario.', checkpoint: 'No demuestra inercia, motor físico, timing de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es determinística del host nativo POSIX y de la planta discreta; no es evidencia de motor físico, hardware, HIL ni certificación.',
    },
    {
      id: 'edge-counter-pulses', exampleId: 'edge_counter', requiredScenario: 'EdgeCounter', sourcePath: 'src/EdgeCounter.st', scenarioPath: 'tests/edge-counter.scenario.json',
      title: 'Flancos y contador de pulsos', summary: 'Usá R_TRIG y CTU para contar tres pulsos discretos y resetear el umbral.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá PulseInput, Reset, Edge, Count y CountReached en src/EdgeCounter.st.', checkpoint: 'R_TRIG convierte cada flanco ascendente en un pulso de un scan; CTU cuenta esos pulsos.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá cuándo el contador alcanza PV=3.', checkpoint: 'CountReached permanece OFF a 0, 10 y 30 ms; enciende a 50 tras el tercer flanco; vuelve OFF a 70 con Reset.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/EdgeCounter.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario EdgeCounter.', checkpoint: 'El escenario requerido se llama EdgeCounter.' },
        { title: 'Observá', body: 'Compará los eventos de 10, 30, 50 y 70 ms con la salida CountReached.', checkpoint: 'El tercer pulso alcanza PV=3; Reset domina y devuelve CountReached a OFF.' },
        { title: 'Reflexioná', body: 'Las assertions AT/RISING/FALLING cubren esta secuencia lógica discreta.', checkpoint: 'No demuestran rebote, pulsos eléctricos, timing de hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es del host nativo POSIX; no es evidencia de sensor físico, rebote, hardware, HIL ni certificación.',
    },
    {
      id: 'scan-cycle-one-scan-memory', exampleId: 'scan_snapshot', requiredScenario: 'ScanSnapshot', sourcePath: 'src/ScanSnapshot.st', scenarioPath: 'tests/scan-snapshot.scenario.json',
      title: 'Ciclo de scan y memoria de un ciclo', summary: 'Seguí cómo una entrada produce una salida actual y una copia demorada un scan.',
      stages: [
        { title: 'Objetivo', body: 'Ubicá Button, Previous, Current, Delayed y RisingPulse en src/ScanSnapshot.st.', checkpoint: 'Previous se actualiza al final del scan.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá los cuatro samples registrados.', checkpoint: '000@0, 101@10, 010@20, 000@30.' },
        { title: 'Editá', body: 'Agregá solamente un comentario explicativo inocuo en src/ScanSnapshot.st. Esta edición no se corrige automáticamente.', checkpoint: 'El comportamiento del programa debe permanecer sin cambios.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente el escenario ScanSnapshot.', checkpoint: 'El escenario requerido se llama ScanSnapshot.' },
        { title: 'Observá', body: 'Compará 10, 20 y 30 ms: RisingPulse dura un scan y Delayed conserva la copia demorada.', checkpoint: 'El pulso aparece a 10 ms; Delayed aparece a 20 ms y vuelve OFF a 30 ms.' },
        { title: 'Evidencia', body: 'AT/RISING/FALLING/NEVER cubren el escenario; los hashes y la traza pertenecen al host.', checkpoint: 'La evidencia registrada es del escenario host ejecutado.' },
        { title: 'Reflexioná', body: 'Actualizar Previous antes rompería el detector de flanco.', checkpoint: 'La memoria debe conservar el valor anterior hasta el final del scan.' },
      ],
      scope: 'La evidencia de Tests es del runtime nativo POSIX host con una única tarea de 10 ms; no demuestra timing de target, snapshot bajo interrupciones físicas, rebote eléctrico, HIL ni certificación.',
    },
    {
      id: 'temporal-assertions-jam-fault', exampleId: 'conveyor_01', requiredScenario: 'Conveyor01', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-01.scenario.json',
      title: 'Assertions temporales y falla por atasco', summary: 'Leé los contratos temporales del escenario Conveyor01 y contrastalos con la planta registrada.',
      stages: [
        { title: 'Objetivo', body: 'Usá src/Conveyor.st y tests/conveyor-01.scenario.json para separar la lógica de sus contratos temporales.', checkpoint: 'El starter debe recuperar el lockout host antes de aprobar el escenario visible.' },
        { title: 'Predecí', body: 'Antes de ejecutar, anticipá qué prueban las dos assertions AT. Leé RISING desde 20 ms dentro de 10 ms, NEVER con desviador activo y cinta apagada, WITHIN desde 50 ms con ventana 0 y FOR por 30 ms.', checkpoint: 'AT exige BeltCommand, DiverterCommand y FaultLamp OFF a 0 ms y BeltCommand ON a 10 ms. RISING alcanza DiverterCommand a más tardar a 30 ms; WITHIN exige Belt OFF y FaultLamp ON a 50 ms; FOR sostiene ese estado de 50 a 80 ms.' },
        { title: 'Editá', body: 'Corregí el lockout host del starter. Leé RISING desde 20 ms dentro de 10 ms, NEVER con desviador activo y cinta apagada, WITHIN desde 50 ms con ventana 0 y FOR por 30 ms.', checkpoint: 'Guardá: RISING alcanza DiverterCommand a más tardar a 30 ms; WITHIN exige Belt OFF y FaultLamp ON a 50 ms; FOR sostiene ese estado de 50 a 80 ms; el escenario visible debe pasar con evidencia host guardada.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente Conveyor01.', checkpoint: 'El escenario requerido se llama Conveyor01 y contiene seis assertions.' },
        { title: 'Contrastá', body: 'Compará assertions, traza y planta registrada: la clasificación aparece antes del atasco; a 50 ms la cinta se apaga y la falla queda activa.', checkpoint: 'La planta registrada muestra la secuencia discreta, no una medición física.' },
        { title: 'Reflexioná', body: 'NEVER evita una combinación lógica incompatible dentro de este escenario; Reset a 60 ms no libera el fallo mientras el atasco inyectado sigue presente.', checkpoint: 'Un atasco inyectado no demuestra falla física, despeje físico, timing de target, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es del runtime nativo POSIX host y de la planta discreta; el atasco inyectado no es una falla física, despeje físico, timing de target, HIL ni certificación.',
    },
    {
      id: 'conveyor-two-parts-diagnosis', exampleId: 'conveyor_01', requiredScenario: 'ConveyorTwoParts', sourcePath: 'src/Conveyor.st', scenarioPath: 'tests/conveyor-two-parts.scenario.json',
      title: 'Diagnóstico reproducible: dos piezas, una decisión', summary: 'Usá el calendario versionado para distinguir una pieza metálica de una no metálica sin inventar observabilidad.',
      stages: [
        { title: 'Ubicá', body: 'Ubicá PartAtClassifier, MetalDetected, PartAtDiverter y MetalLatched en src/Conveyor.st.', checkpoint: 'MetalLatched se activa con clasificador+metal y se limpia al llegar al desviador.' },
        { title: 'Predecí', body: 'La primera pieza es metálica y la segunda no metálica.', checkpoint: 'Esperá desvío sólo para la primera; Belt queda activo para ambas.' },
        { title: 'Leé el calendario', body: 'El JSON agenda clasificador→desviador 20→30 ms y 50→70 ms, con tick de 10 ms hasta 80 ms.', checkpoint: 'Las tres assertions son AT@30 Belt=true/Diverter=true, AT@70 Belt=true/Diverter=false y NEVER Diverter=true con Belt=false.' },
        { title: 'Ejecutá', body: 'En Tests, elegí el zplc.json guardado y ejecutá únicamente ConveyorTwoParts.', checkpoint: 'El escenario requerido se llama ConveyorTwoParts.' },
        { title: 'Diagnosticá', body: 'La matriz de Tests prueba outputs host: compará las muestras de 30 y 70 ms.', checkpoint: 'No prueba ni registra inputs, piezas físicas ni el estado interno MetalLatched.' },
        { title: 'Límites', body: 'Repetí el mismo escenario para una decisión reproducible sobre outputs del host.', checkpoint: 'No demuestra sensores o piezas físicas, timing de target, hardware, HIL ni certificación.' },
      ],
      scope: 'La evidencia de Tests es del runtime nativo POSIX host con inputs programados por escenario; no es evidencia de sensores ni piezas físicas, timing de target, hardware, HIL ni certificación.',
    },
]);

export const learnFaultCasesEsV1: Readonly<Record<LearnLessonId, readonly string[]>> = Object.freeze({
  'motor-start-stop-safe': ['El starter pierde el enclavamiento al soltar Start; implementá baja por Stop, EStop y sobrecarga.'],
  'pedestrian-crossing-states': ['El starter nunca entra en fase peatonal ante un pedido; implementá estados mutuamente excluyentes.'],
  'tank-level-fault-reset': ['El starter sigue funcionando ante una falla de bomba; enclavá la alarma y exigí reset antes de recuperar.'],
  'conveyor-classification-jam': ['El starter no bloquea la cinta ante el atasco determinista; detenela mientras la planta informa JamDetected.'],
  'blinky-ladder-timer-feedback': ['El starter nunca conmuta LED_Output; agregá un oscilador TON con realimentación acotada.'],
  'motor-plant-feedback': ['El starter pierde Command cuando cae Start; retené el pedido hasta Stop y condicioná Running con AtSpeed.'],
  'edge-counter-pulses': ['El starter nunca alcanza el tercer flanco ascendente; agregá R_TRIG y CTU con PV=3.'],
  'scan-cycle-one-scan-memory': ['El starter no tiene memoria de un scan; retené Previous y calculá el flanco antes de actualizarlo.'],
  'temporal-assertions-jam-fault': ['El starter omite el lockout de atasco host; detené Belt mientras JamDetected esté activo.'],
  'conveyor-two-parts-diagnosis': ['El starter nunca enclava metal para el desviador; liberalo recién cuando la pieza metálica llega al desviador.'],
});
