/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/sparkplug_b.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(org_eclipse_tahu_protobuf_PropertyValue, org_eclipse_tahu_protobuf_PropertyValue, AUTO)


PB_BIND(org_eclipse_tahu_protobuf_PropertySet, org_eclipse_tahu_protobuf_PropertySet, AUTO)


PB_BIND(org_eclipse_tahu_protobuf_MetaData, org_eclipse_tahu_protobuf_MetaData, AUTO)


PB_BIND(org_eclipse_tahu_protobuf_Metric, org_eclipse_tahu_protobuf_Metric, 2)


PB_BIND(org_eclipse_tahu_protobuf_Payload, org_eclipse_tahu_protobuf_Payload, 4)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

