/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ORG_ECLIPSE_TAHU_PROTOBUF_PROTO_SPARKPLUG_B_PB_H_INCLUDED
#define PB_ORG_ECLIPSE_TAHU_PROTOBUF_PROTO_SPARKPLUG_B_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _org_eclipse_tahu_protobuf_PropertyValue {
    uint32_t type;
    bool is_null;
    pb_size_t which_value;
    union _org_eclipse_tahu_protobuf_PropertyValue_value {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[32]; /* skipping ExtensionValue, PropertySet for embedded */
    } value;
} org_eclipse_tahu_protobuf_PropertyValue;

typedef struct _org_eclipse_tahu_protobuf_PropertySet {
    pb_size_t keys_count;
    char keys[4][16];
    pb_size_t values_count;
    org_eclipse_tahu_protobuf_PropertyValue values[4];
} org_eclipse_tahu_protobuf_PropertySet;

typedef struct _org_eclipse_tahu_protobuf_MetaData {
    bool is_multi_part;
    char content_type[16];
    uint64_t size;
    uint64_t seq;
    char file_name[16];
    char file_type[16];
    char md5[33];
    char description[32];
} org_eclipse_tahu_protobuf_MetaData;

typedef PB_BYTES_ARRAY_T(32) org_eclipse_tahu_protobuf_Metric_bytes_value_t;
typedef struct _org_eclipse_tahu_protobuf_Metric {
    char name[32];
    uint64_t alias;
    uint64_t timestamp;
    uint32_t datatype;
    bool is_historical;
    bool is_transient;
    bool is_null;
    bool has_metadata;
    org_eclipse_tahu_protobuf_MetaData metadata;
    bool has_properties;
    org_eclipse_tahu_protobuf_PropertySet properties;
    pb_size_t which_value;
    union _org_eclipse_tahu_protobuf_Metric_value {
        uint32_t int_value;
        uint64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        char string_value[64];
        org_eclipse_tahu_protobuf_Metric_bytes_value_t bytes_value; /* skipping DataSet, Template for embedded */
    } value;
} org_eclipse_tahu_protobuf_Metric;

typedef PB_BYTES_ARRAY_T(64) org_eclipse_tahu_protobuf_Payload_body_t;
typedef struct _org_eclipse_tahu_protobuf_Payload {
    uint64_t timestamp;
    pb_size_t metrics_count;
    org_eclipse_tahu_protobuf_Metric metrics[32];
    uint64_t seq;
    char uuid[37];
    org_eclipse_tahu_protobuf_Payload_body_t body;
} org_eclipse_tahu_protobuf_Payload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define org_eclipse_tahu_protobuf_PropertyValue_init_default {0, 0, 0, {0}}
#define org_eclipse_tahu_protobuf_PropertySet_init_default {0, {"", "", "", ""}, 0, {org_eclipse_tahu_protobuf_PropertyValue_init_default, org_eclipse_tahu_protobuf_PropertyValue_init_default, org_eclipse_tahu_protobuf_PropertyValue_init_default, org_eclipse_tahu_protobuf_PropertyValue_init_default}}
#define org_eclipse_tahu_protobuf_MetaData_init_default {0, "", 0, 0, "", "", "", ""}
#define org_eclipse_tahu_protobuf_Metric_init_default {"", 0, 0, 0, 0, 0, 0, false, org_eclipse_tahu_protobuf_MetaData_init_default, false, org_eclipse_tahu_protobuf_PropertySet_init_default, 0, {0}}
#define org_eclipse_tahu_protobuf_Payload_init_default {0, 0, {org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default, org_eclipse_tahu_protobuf_Metric_init_default}, 0, "", {0, {0}}}
#define org_eclipse_tahu_protobuf_PropertyValue_init_zero {0, 0, 0, {0}}
#define org_eclipse_tahu_protobuf_PropertySet_init_zero {0, {"", "", "", ""}, 0, {org_eclipse_tahu_protobuf_PropertyValue_init_zero, org_eclipse_tahu_protobuf_PropertyValue_init_zero, org_eclipse_tahu_protobuf_PropertyValue_init_zero, org_eclipse_tahu_protobuf_PropertyValue_init_zero}}
#define org_eclipse_tahu_protobuf_MetaData_init_zero {0, "", 0, 0, "", "", "", ""}
#define org_eclipse_tahu_protobuf_Metric_init_zero {"", 0, 0, 0, 0, 0, 0, false, org_eclipse_tahu_protobuf_MetaData_init_zero, false, org_eclipse_tahu_protobuf_PropertySet_init_zero, 0, {0}}
#define org_eclipse_tahu_protobuf_Payload_init_zero {0, 0, {org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero, org_eclipse_tahu_protobuf_Metric_init_zero}, 0, "", {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define org_eclipse_tahu_protobuf_PropertyValue_type_tag 1
#define org_eclipse_tahu_protobuf_PropertyValue_is_null_tag 2
#define org_eclipse_tahu_protobuf_PropertyValue_int_value_tag 3
#define org_eclipse_tahu_protobuf_PropertyValue_long_value_tag 4
#define org_eclipse_tahu_protobuf_PropertyValue_float_value_tag 5
#define org_eclipse_tahu_protobuf_PropertyValue_double_value_tag 6
#define org_eclipse_tahu_protobuf_PropertyValue_boolean_value_tag 7
#define org_eclipse_tahu_protobuf_PropertyValue_string_value_tag 8
#define org_eclipse_tahu_protobuf_PropertySet_keys_tag 1
#define org_eclipse_tahu_protobuf_PropertySet_values_tag 2
#define org_eclipse_tahu_protobuf_MetaData_is_multi_part_tag 1
#define org_eclipse_tahu_protobuf_MetaData_content_type_tag 2
#define org_eclipse_tahu_protobuf_MetaData_size_tag 3
#define org_eclipse_tahu_protobuf_MetaData_seq_tag 4
#define org_eclipse_tahu_protobuf_MetaData_file_name_tag 5
#define org_eclipse_tahu_protobuf_MetaData_file_type_tag 6
#define org_eclipse_tahu_protobuf_MetaData_md5_tag 7
#define org_eclipse_tahu_protobuf_MetaData_description_tag 8
#define org_eclipse_tahu_protobuf_Metric_name_tag 1
#define org_eclipse_tahu_protobuf_Metric_alias_tag 2
#define org_eclipse_tahu_protobuf_Metric_timestamp_tag 3
#define org_eclipse_tahu_protobuf_Metric_datatype_tag 4
#define org_eclipse_tahu_protobuf_Metric_is_historical_tag 5
#define org_eclipse_tahu_protobuf_Metric_is_transient_tag 6
#define org_eclipse_tahu_protobuf_Metric_is_null_tag 7
#define org_eclipse_tahu_protobuf_Metric_metadata_tag 8
#define org_eclipse_tahu_protobuf_Metric_properties_tag 9
#define org_eclipse_tahu_protobuf_Metric_int_value_tag 10
#define org_eclipse_tahu_protobuf_Metric_long_value_tag 11
#define org_eclipse_tahu_protobuf_Metric_float_value_tag 12
#define org_eclipse_tahu_protobuf_Metric_double_value_tag 13
#define org_eclipse_tahu_protobuf_Metric_boolean_value_tag 14
#define org_eclipse_tahu_protobuf_Metric_string_value_tag 15
#define org_eclipse_tahu_protobuf_Metric_bytes_value_tag 16
#define org_eclipse_tahu_protobuf_Payload_timestamp_tag 1
#define org_eclipse_tahu_protobuf_Payload_metrics_tag 2
#define org_eclipse_tahu_protobuf_Payload_seq_tag 3
#define org_eclipse_tahu_protobuf_Payload_uuid_tag 4
#define org_eclipse_tahu_protobuf_Payload_body_tag 5

/* Struct field encoding specification for nanopb */
#define org_eclipse_tahu_protobuf_PropertyValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     is_null,           2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,value.int_value),   3) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,value.long_value),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   5) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   6) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,value.boolean_value),   7) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   8)
#define org_eclipse_tahu_protobuf_PropertyValue_CALLBACK NULL
#define org_eclipse_tahu_protobuf_PropertyValue_DEFAULT NULL

#define org_eclipse_tahu_protobuf_PropertySet_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   keys,              1) \
X(a, STATIC,   REPEATED, MESSAGE,  values,            2)
#define org_eclipse_tahu_protobuf_PropertySet_CALLBACK NULL
#define org_eclipse_tahu_protobuf_PropertySet_DEFAULT NULL
#define org_eclipse_tahu_protobuf_PropertySet_values_MSGTYPE org_eclipse_tahu_protobuf_PropertyValue

#define org_eclipse_tahu_protobuf_MetaData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_multi_part,     1) \
X(a, STATIC,   SINGULAR, STRING,   content_type,      2) \
X(a, STATIC,   SINGULAR, UINT64,   size,              3) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               4) \
X(a, STATIC,   SINGULAR, STRING,   file_name,         5) \
X(a, STATIC,   SINGULAR, STRING,   file_type,         6) \
X(a, STATIC,   SINGULAR, STRING,   md5,               7) \
X(a, STATIC,   SINGULAR, STRING,   description,       8)
#define org_eclipse_tahu_protobuf_MetaData_CALLBACK NULL
#define org_eclipse_tahu_protobuf_MetaData_DEFAULT NULL

#define org_eclipse_tahu_protobuf_Metric_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT64,   alias,             2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, STATIC,   SINGULAR, UINT32,   datatype,          4) \
X(a, STATIC,   SINGULAR, BOOL,     is_historical,     5) \
X(a, STATIC,   SINGULAR, BOOL,     is_transient,      6) \
X(a, STATIC,   SINGULAR, BOOL,     is_null,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  properties,        9) \
X(a, STATIC,   ONEOF,    UINT32,   (value,int_value,value.int_value),  10) \
X(a, STATIC,   ONEOF,    UINT64,   (value,long_value,value.long_value),  11) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),  12) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),  13) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,value.boolean_value),  14) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),  15) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),  16)
#define org_eclipse_tahu_protobuf_Metric_CALLBACK NULL
#define org_eclipse_tahu_protobuf_Metric_DEFAULT NULL
#define org_eclipse_tahu_protobuf_Metric_metadata_MSGTYPE org_eclipse_tahu_protobuf_MetaData
#define org_eclipse_tahu_protobuf_Metric_properties_MSGTYPE org_eclipse_tahu_protobuf_PropertySet

#define org_eclipse_tahu_protobuf_Payload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  metrics,           2) \
X(a, STATIC,   SINGULAR, UINT64,   seq,               3) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              4) \
X(a, STATIC,   SINGULAR, BYTES,    body,              5)
#define org_eclipse_tahu_protobuf_Payload_CALLBACK NULL
#define org_eclipse_tahu_protobuf_Payload_DEFAULT NULL
#define org_eclipse_tahu_protobuf_Payload_metrics_MSGTYPE org_eclipse_tahu_protobuf_Metric

extern const pb_msgdesc_t org_eclipse_tahu_protobuf_PropertyValue_msg;
extern const pb_msgdesc_t org_eclipse_tahu_protobuf_PropertySet_msg;
extern const pb_msgdesc_t org_eclipse_tahu_protobuf_MetaData_msg;
extern const pb_msgdesc_t org_eclipse_tahu_protobuf_Metric_msg;
extern const pb_msgdesc_t org_eclipse_tahu_protobuf_Payload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define org_eclipse_tahu_protobuf_PropertyValue_fields &org_eclipse_tahu_protobuf_PropertyValue_msg
#define org_eclipse_tahu_protobuf_PropertySet_fields &org_eclipse_tahu_protobuf_PropertySet_msg
#define org_eclipse_tahu_protobuf_MetaData_fields &org_eclipse_tahu_protobuf_MetaData_msg
#define org_eclipse_tahu_protobuf_Metric_fields &org_eclipse_tahu_protobuf_Metric_msg
#define org_eclipse_tahu_protobuf_Payload_fields &org_eclipse_tahu_protobuf_Payload_msg

/* Maximum encoded size of messages (where known) */
#define ORG_ECLIPSE_TAHU_PROTOBUF_PROTO_SPARKPLUG_B_PB_H_MAX_SIZE org_eclipse_tahu_protobuf_Payload_size
#define org_eclipse_tahu_protobuf_MetaData_size  142
#define org_eclipse_tahu_protobuf_Metric_size    520
#define org_eclipse_tahu_protobuf_Payload_size   16862
#define org_eclipse_tahu_protobuf_PropertySet_size 240
#define org_eclipse_tahu_protobuf_PropertyValue_size 41

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
