/**
 * @file zplc_debug.h
 * @brief ZPLC Hardware-in-the-Loop Debug API
 *
 * SPDX-License-Identifier: MIT
 *
 * This header declares the debug output API for HIL (Hardware-in-the-Loop)
 * testing. When enabled, the runtime outputs JSON-formatted trace information
 * via the Zephyr shell for parsing by the HIL test framework.
 *
 * The debug output is runtime-controllable (not compile-time), allowing
 * the same firmware to be used in production and testing modes.
 *
 * Protocol: Line-based JSON with CRLF terminators.
 * See: specs/002-hil-testing/contracts/debug-protocol.md
 *
 * @note All functions are guarded by CONFIG_ZPLC_HIL_DEBUG.
 *       When disabled, the functions are defined as no-ops with zero overhead.
 */

#ifndef ZPLC_DEBUG_H
#define ZPLC_DEBUG_H

/* Include Zephyr autoconf to get CONFIG_* macros.
 * This file is generated by Zephyr's build system and contains all Kconfig values.
 * For non-Zephyr builds, this include will fail gracefully or be skipped. */
#if __has_include(<zephyr/autoconf.h>)
#include <zephyr/autoconf.h>
#endif

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Debug Mode Enum
 * ============================================================================ */

/**
 * @brief HIL debug output modes.
 *
 * Controls the verbosity of debug output. Higher modes produce more output
 * but consume more serial bandwidth.
 */
typedef enum {
    HIL_MODE_OFF = 0,      /**< No debug output (production mode) */
    HIL_MODE_SUMMARY = 1,  /**< Per-cycle summaries only (~100-500 B/s) */
    HIL_MODE_VERBOSE = 2   /**< Per-opcode trace (~5-10 KB/s) */
} hil_mode_t;

/* ============================================================================
 * Configuration Check
 * ============================================================================ */

#ifdef CONFIG_ZPLC_HIL_DEBUG

/* Forward declaration for Zephyr shell */
struct shell;

/* ============================================================================
 * Mode Control
 * ============================================================================ */

/**
 * @brief Set the HIL debug output mode.
 *
 * @param mode The desired debug mode
 */
void hil_set_mode(hil_mode_t mode);

/**
 * @brief Get the current HIL debug output mode.
 *
 * @return Current debug mode
 */
hil_mode_t hil_get_mode(void);

/**
 * @brief Set the shell instance for debug output.
 *
 * Must be called before any trace functions. Typically called by the
 * `zplc hil mode` shell command.
 *
 * @param sh Pointer to shell instance
 */
void hil_set_shell(const struct shell *sh);

/* ============================================================================
 * Trace Functions
 * ============================================================================ */

/**
 * @brief Trace an opcode execution.
 *
 * Emits: {"t":"opcode","op":"ADD","pc":18,"sp":2,"tos":7}
 *
 * Only outputs in HIL_MODE_VERBOSE.
 *
 * @param op    Opcode value (from zplc_opcode_t)
 * @param pc    Program counter BEFORE execution
 * @param sp    Stack pointer AFTER execution
 * @param tos   Top of stack value AFTER execution (signed)
 */
void hil_trace_opcode(uint8_t op, uint16_t pc, uint8_t sp, int32_t tos);

/**
 * @brief Trace a function block execution.
 *
 * Emits: {"t":"fb","name":"TON","id":0,"q":true,"et":100}
 *
 * Outputs in HIL_MODE_SUMMARY and HIL_MODE_VERBOSE.
 *
 * @param name  Function block type name (e.g., "TON", "CTU")
 * @param id    Instance ID (0-255)
 * @param q     Q output value
 * @param et_or_cv  Elapsed time (timers) or current value (counters), -1 if N/A
 */
void hil_trace_fb(const char *name, uint8_t id, bool q, int32_t et_or_cv);

/**
 * @brief Trace a task completion.
 *
 * Emits: {"t":"task","id":1,"start":1000,"end":1045,"us":45,"ovr":false}
 *
 * Outputs in HIL_MODE_SUMMARY and HIL_MODE_VERBOSE.
 *
 * @param id        Task ID (0-7)
 * @param start_ms  Task start time (ms since boot)
 * @param end_ms    Task end time (ms since boot)
 * @param us        Execution time in microseconds
 * @param overrun   True if task overran its period
 */
void hil_trace_task(uint8_t id, uint32_t start_ms, uint32_t end_ms,
                    uint32_t us, bool overrun);

/**
 * @brief Trace a VM cycle completion.
 *
 * Emits: {"t":"cycle","n":100,"us":850,"tasks":3}
 *
 * Outputs in HIL_MODE_SUMMARY and HIL_MODE_VERBOSE.
 *
 * @param n     Cycle number (0-2^31)
 * @param us    Total cycle time in microseconds
 * @param tasks Number of tasks executed this cycle
 */
void hil_trace_cycle(uint32_t n, uint32_t us, uint8_t tasks);

/**
 * @brief Trace a VM error.
 *
 * Emits: {"t":"error","code":3,"msg":"DIV_BY_ZERO","pc":42}
 *
 * Always outputs regardless of mode (errors are always important).
 *
 * @param code  Error code (from zplc_vm_error_t)
 * @param msg   Human-readable error message
 * @param pc    Program counter where error occurred
 */
void hil_trace_error(uint8_t code, const char *msg, uint16_t pc);

/**
 * @brief Trace a watched variable change.
 *
 * Emits: {"t":"watch","addr":8192,"type":"i32","val":42}
 *
 * @param addr  Variable address
 * @param type  Type string: "i8", "i16", "i32", "u8", "u16", "u32", "f32", "bool"
 * @param val   Current value (as signed 32-bit, caller converts)
 */
void hil_trace_watch(uint16_t addr, const char *type, int32_t val);

/**
 * @brief Send the ready signal on boot.
 *
 * Emits: {"t":"ready","fw":"1.4.0","caps":["sched","hil"]}
 *
 * Should be called once after boot when shell is ready.
 *
 * @param fw_version  Firmware version string (e.g., "1.4.0")
 * @param caps        Comma-separated capability list (e.g., "sched,hil,sfc")
 */
void hil_send_ready(const char *fw_version, const char *caps);

/**
 * @brief Send a command acknowledgment.
 *
 * Emits: {"t":"ack","cmd":"mode","val":"verbose","ok":true}
 *
 * @param cmd   Command name that was executed
 * @param val   Value that was set
 * @param ok    True if command succeeded
 * @param err   Error message if ok is false, NULL otherwise
 */
void hil_send_ack(const char *cmd, const char *val, bool ok, const char *err);

/* ============================================================================
 * Opcode Name Lookup
 * ============================================================================ */

/**
 * @brief Get the string name for an opcode.
 *
 * @param op Opcode value
 * @return Opcode name string (e.g., "ADD", "PUSH32"), or "???" if unknown
 */
const char *hil_opcode_name(uint8_t op);

/* ============================================================================
 * Error Message Lookup
 * ============================================================================ */

/**
 * @brief Get the string name for a VM error code.
 *
 * @param code Error code (from zplc_vm_error_t)
 * @return Error name string (e.g., "DIV_BY_ZERO"), or "UNKNOWN" if invalid
 */
const char *hil_error_name(uint8_t code);

#else /* CONFIG_ZPLC_HIL_DEBUG not defined */

/* ============================================================================
 * No-op Stubs (Zero Overhead)
 * ============================================================================
 *
 * When HIL debug is disabled, all functions become empty inline stubs.
 * The compiler will optimize these away completely.
 */

#define hil_set_mode(mode)           ((void)0)
#define hil_get_mode()               (HIL_MODE_OFF)
#define hil_set_shell(sh)            ((void)0)

#define hil_trace_opcode(op, pc, sp, tos)                  ((void)0)
#define hil_trace_fb(name, id, q, et_or_cv)                ((void)0)
#define hil_trace_task(id, start, end, us, ovr)            ((void)0)
#define hil_trace_cycle(n, us, tasks)                      ((void)0)
#define hil_trace_error(code, msg, pc)                     ((void)0)
#define hil_trace_watch(addr, type, val)                   ((void)0)
#define hil_send_ready(fw, caps)                           ((void)0)
#define hil_send_ack(cmd, val, ok, err)                    ((void)0)

#define hil_opcode_name(op)          ("???")
#define hil_error_name(code)         ("UNKNOWN")

#endif /* CONFIG_ZPLC_HIL_DEBUG */

#ifdef __cplusplus
}
#endif

#endif /* ZPLC_DEBUG_H */
