/**
 * Generated Code Dialog
 * 
 * Modal dialog to display and copy generated code
 * (Structured Text from visual languages, or Assembly from compiler).
 */

import { useState } from 'react';
import { Copy, Check, Download, FileText } from 'lucide-react';
import { Modal } from './Modal';

interface GeneratedCodeDialogProps {
  isOpen: boolean;
  onClose: () => void;
  sourceLanguage: 'FBD' | 'LD' | 'SFC' | 'ASM';
  generatedCode: string;
  /** Optional: callback to create a new file with this content */
  onCreateFile?: (code: string) => void;
}

export function GeneratedCodeDialog({
  isOpen,
  onClose,
  sourceLanguage,
  generatedCode,
  onCreateFile,
}: GeneratedCodeDialogProps) {
  const [copied, setCopied] = useState(false);

  const isAssembly = sourceLanguage === 'ASM';
  const title = isAssembly 
    ? 'Generated ZPLC Assembly' 
    : `Generated Structured Text (from ${sourceLanguage})`;
  
  const fileExtension = isAssembly ? '.asm' : '.st';
  const description = isAssembly
    ? 'This is the intermediate assembly code generated by the compiler. Useful for debugging and optimization.'
    : `This code was auto-generated from your ${sourceLanguage} diagram. You can copy it, create a new .st file, or use it for debugging.`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Failed to copy to clipboard:', e);
    }
  };

  const handleCreateFile = () => {
    onCreateFile?.(generatedCode);
    onClose();
  };

  const lineCount = generatedCode.split('\n').length;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={title}
      widthClass="max-w-4xl"
    >
      {/* Stats & Actions Bar */}
      <div className="flex items-center justify-between px-4 py-2 bg-[var(--color-surface-700)] border-b border-[var(--color-surface-600)]">
        <div className="flex items-center gap-4 text-sm text-[var(--color-surface-300)]">
          <span className="flex items-center gap-1">
            <FileText size={14} />
            {lineCount} lines
          </span>
          <span>
            {generatedCode.length.toLocaleString()} characters
          </span>
        </div>
        
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded text-sm bg-[var(--color-surface-600)] hover:bg-[var(--color-surface-500)] text-[var(--color-surface-100)] transition-colors"
          >
            {copied ? (
              <>
                <Check size={14} className="text-green-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy size={14} />
                Copy
              </>
            )}
          </button>
          
          {onCreateFile && (
            <button
              onClick={handleCreateFile}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded text-sm bg-[var(--color-accent-blue)] hover:opacity-90 text-white transition-colors"
            >
              <Download size={14} />
              Create {fileExtension} File
            </button>
          )}
        </div>
      </div>

      {/* Code Display */}
      <div className="p-4 overflow-auto max-h-[60vh]">
        <pre className="text-sm font-mono leading-relaxed text-[var(--color-surface-100)] whitespace-pre-wrap">
          <code>{generatedCode}</code>
        </pre>
      </div>

      {/* Footer */}
      <div className="px-4 py-3 border-t border-[var(--color-surface-600)] bg-[var(--color-surface-700)]">
        <p className="text-xs text-[var(--color-surface-400)]">
          {description}
        </p>
      </div>
    </Modal>
  );
}
